name: vexana_inspector
description: Vexana Inspector is a package that helps you to debug your network requests.
version: 1.0.0
homepage: https://pub.dev/publishers/vb10.dev
repository: https://github.com/VB10/vexana_inspector

environment:
  sdk: ">=2.18.3 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  # Core
  dio: ^5.1.1
  equatable: ^2.0.5

  # State Management
  flutter_bloc: ^8.1.2

  # Utils
  kartal: ^2.8.0
  share_plus: ^6.3.4
  flutter_json_view: ^1.0.0
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^4.0.0+1
