name: vexana_inspector
description: A new Flutter package project.
version: 0.0.1
homepage: www.vexana.com
environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  # Core
  dio: ^5.1.1
  equatable: ^2.0.5

  # State Management
  flutter_bloc: ^8.1.2

  # Utils
  kartal: ^2.8.0
  share_plus: ^6.3.1
  flutter_json_view: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^4.0.0+1
