name: vexana_inspector
description: Vexana Inspector is a package that helps you to debug your network requests.
version: 2.2.2
homepage: https://pub.dev/publishers/vb10.dev
repository: https://github.com/VB10/vexana_inspector
issue_tracker: https://github.com/VB10/vexana_inspector/issues
screenshots:
  - description: 'Vexana Inspector usage'
    path: github/example.png

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  dio: ^5.1.1
  equatable: ^2.0.5

  # State Management
  flutter_bloc: ^8.1.2

  # Utils
  kartal: ^4.0.2
  flutter_json_view: ^1.0.0
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^5.1.0
